# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 603cc7ab94cc794b3202e6f47256e95b33997b26873518ed680b2351c5a394fcfa73d98861083eba83e5bb32f699ccb359dc82ebcf659b5b30c90f660266a7f2

test:
  secret_key_base: 2c0c8598d2db4332e842fc31960d2dcd1dd9809c2f566da97b13f7b42af5837d2c8a1ba94aa165937eebed700ba6d439ca15dfedd554c9a2fb2691954b18f84e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
